#!/usr/bin/env bash

test -c /dev/plcm_drv && echo "OK" || /etc/init.d/make_node_plcm start

if [ "$#" -eq 1 ]; then
    /bin/plcm_message --message-line-1 $(echo $1 | tr '_' ' ')
    echo $1
fi

if [ "$#" -eq 2 ]; then
    /bin/plcm_message --message-line-1 "$(echo $1 | tr '_' ' ')"
    /bin/plcm_message --message-line-2 "$(echo $2 | tr '_' ' ')"
    echo $1
    echo $2
fi
