#!/usr/bin/env bash

if [ "$#" -eq 1 ]; then
    /bin/plcm_message --message-line-1 $1
    echo $1
fi

if [ "$#" -eq 2 ]; then
    /bin/plcm_message --message-line-1 $1
    /bin/plcm_message --message-line-2 $2
    echo $1
    echo $2
fi
